### ISSUE TITLE
Unable to load images in production

### ISSUE THREAD

**Issue by aju126** [rainchen/react-rails-img#11]
i'v created a rails app with react-rails gem.
I'v used react-rails-img for loading images in a react component. It works fine in development but fails in production with no route error.
code : 
```
<Img src="/assets/pic.png" alt="logo" className="img-circle" id="img-circle"/>
```

**Comment by rainchen** [comment]
@rockcoderAJ did you run `rake assets:precompile` before starting the rails server?
