### ISSUE TITLE
Works Fine Until I Try To Render a Text Component Over Image

### ISSUE THREAD

**Issue by jesskrich** [rainchen/react-rails-img#12]
Is this a bug or was it not intended to allow for such functionality? Really love it and would work for most situations, but not the specific one I need to accomplish.

***EDIT: Sorry! Never mind. Works just fine. I was just being dumb and it's been a minute since I've used React. Thanks so much! Love this.

**Comment by rainchen** [comment]
@jesskrich glad this project is helpful to you, why not give it a star :)
