### ISSUE TITLE
Question: where is 'assets' defined in this file?

### ISSUE THREAD

**Issue by adiakritos** [rainchen/react-rails-img#14]
In this file: 

    `react-rails-img/vendor/assets/javascripts/react_rails_img.js.jsx.erb`

On line 8:

    `images_enumerator = defined?(assets) ? assets.each_file : Dir["#{images_dir}**/*.*"]`

I don't see where 'assets' is defined anywhere. I haven't run this code yet, I'm assuming this does work. I just don't understand how that variable has anything in it.

**Comment by rainchen** [comment]
@adiakritos 

if you don't ask this question, I alomost forgot this `assets` helper. 

The `assets` helper was defined by gem `sprockets-rails` <= v2.3.3
it was a shortcut for accessing  `Sprockets::Rails::Helper.assets`, as:

```
# https://github.com/rails/sprockets-rails/blob/v2.3.3/lib/sprockets/rails/helper.rb#L16-L18
def assets
  Sprockets::Rails::Helper.assets
end
```

But it was removed after gem `sprockets-rails` > 3.0.0 (in 2016)
checkout source [helper.rb](https://github.com/rails/sprockets-rails/blob/v3.0.0/lib/sprockets/rails/helper.rb)

It won't be available for rails projects which started after 2016.
