### ISSUE TITLE
Can't get it to work production

### ISSUE THREAD

**Issue by yhkang95** [rainchen/react-rails-img#8]
In the documentation it says that if I use `<Img src="/assets/logo.png" />`, the path will be `/assets/logo.png` for development and `/assets/logo-be1f67ffd42a4c1a41bdcc547c5705a3423a2f24bfe930f00398077fe518e6c0.png` for production.

However, I'm getting the same path (non-digested path) for both development and production. I've tried different variations:

`<Img src="/assets/logo.png" />`
`<Img src="logo.png" />`
`imageTag('/assets/logo.png')`
`imageTag('logo.png')`

All of them work well in development, but don't work in production.

I have all my images in `/assets/images`.

Please help me out. Thank you so much!

**Comment by rainchen** [comment]
@yhkang95 which rails version you are using and what kind of production server you are using? Heroku?

**Comment by yhkang95** [comment]
I'm using `rails 4.2.1` on Heroku.

**Comment by rainchen** [comment]
@yhkang95 are you using gem "rails_12factor" to handle static assets? If not, try it

**Comment by rainchen** [comment]
@yhkang95 any feedback?
