### ISSUE TITLE
Doesn't support onClick or Data Attributes

### ISSUE THREAD

**Issue by HCLarsen** [rainchen/react-rails-img#9]
My code looks like this:

`<Img key={key} className="dj-photo" src={allDJs[key].image} alt={allDJs[key].name} onClick={this.selectDJ} data-key={key} />`

But the rendered HTML looks like this:

`<img src="/assets/shok.jpg" alt="DJ Shok" class="dj-photo">`

The onClick and data-key were both dropped in the rendering. Is there a workaround for this, or is this a bug?

**Comment by rainchen** [comment]
@HCLarsen actually this is a known issue. I'm going to fix it.

**Comment by HCLarsen** [comment]
Are there any known workarounds in the meantime?

**Comment by rainchen** [comment]
@HCLarsen was fixed in https://github.com/rainchen/react-rails-img/pull/10 and released as v0.1.6
you just need to update to the latest version in your Gemfile.
